"""
Source Ranking Definitions
Priority: 1 = highest, 8 = lowest
"""

SOURCES = [
    # Primary
    {"name": "NSE India",       "url": "https://www.nseindia.com/",        "rank": 1},
    {"name": "Moneycontrol",    "url": "https://www.moneycontrol.com/",    "rank": 2},
    {"name": "Reuters",         "url": "https://www.reuters.com/markets/", "rank": 3},
    {"name": "TradingView",     "url": "https://www.tradingview.com/news/","rank": 4},
    {"name": "Motilal Oswal",   "url": "https://www.motilaloswal.com/",    "rank": 5},
    # Secondary
    {"name": "Yahoo Finance",   "url": "https://finance.yahoo.com/",       "rank": 6},
    {"name": "Economic Times",  "url": "https://economictimes.indiatimes.com/markets/", "rank": 6},
    {"name": "LiveMint",        "url": "https://www.livemint.com/market/", "rank": 6},
    {"name": "Business Standard","url": "https://www.business-standard.com/markets/", "rank": 6},
    {"name": "Investing.com",   "url": "https://www.investing.com/news/",  "rank": 6},
    {"name": "CNBC TV18",       "url": "https://www.cnbctv18.com/market/", "rank": 6},
    # Community
    {"name": "Reddit",          "url": "https://www.reddit.com/r/IndianStockMarket/", "rank": 7},
    {"name": "FrontPage",       "url": "https://frontpageindia.com/",      "rank": 7},
]

# Ticker symbol → search aliases used for news-headline entity matching and
# stock-analysis resolution. Despite the legacy name, this dict covers
# NIFTY 50 + popular non-NIFTY-50 retail-favorite names (IRCTC, SUZLON,
# IRFC, etc.) so user searches resolve to a proper company name and the
# Google News alias query yields useful results.
NIFTY50_TICKERS = {
    # ── NIFTY 50 core ────────────────────────────────────────────────────
    "RELIANCE":   ["Reliance", "Reliance Industries", "RIL"],
    "TCS":        ["TCS", "Tata Consultancy", "Tata Consultancy Services"],
    "HDFCBANK":   ["HDFC Bank", "HDFC"],
    "INFY":       ["Infosys", "Infy"],
    "HINDUNILVR": ["Hindustan Unilever", "HUL"],
    "ICICIBANK":  ["ICICI Bank", "ICICI"],
    "BAJFINANCE": ["Bajaj Finance"],
    "SBIN":       ["SBI", "State Bank of India", "State Bank"],
    "BHARTIARTL": ["Airtel", "Bharti Airtel"],
    "KOTAKBANK":  ["Kotak Bank", "Kotak Mahindra Bank"],
    "WIPRO":      ["Wipro"],
    "AXISBANK":   ["Axis Bank"],
    "LT":         ["L&T", "Larsen & Toubro", "Larsen and Toubro"],
    "HCLTECH":    ["HCL Tech", "HCL Technologies"],
    "ADANIENT":   ["Adani Enterprises"],
    "ADANIPORTS": ["Adani Ports"],
    "TATAMOTORS": ["Tata Motors"],
    "TATASTEEL":  ["Tata Steel"],
    "MARUTI":     ["Maruti Suzuki", "Maruti"],
    "SUNPHARMA":  ["Sun Pharma", "Sun Pharmaceutical"],
    "TITAN":      ["Titan"],
    "NESTLEIND":  ["Nestle India", "Nestle"],
    "ULTRACEMCO": ["UltraTech Cement"],
    "ASIANPAINT": ["Asian Paints"],
    "ONGC":       ["ONGC", "Oil and Natural Gas"],
    "POWERGRID":  ["Power Grid"],
    "NTPC":       ["NTPC"],
    "COALINDIA":  ["Coal India"],
    "JSWSTEEL":   ["JSW Steel"],
    "INDUSINDBK": ["IndusInd Bank"],
    "M&M":        ["Mahindra & Mahindra", "M&M"],
    "HEROMOTOCO": ["Hero MotoCorp", "Hero Honda"],
    "BAJAJ-AUTO": ["Bajaj Auto"],
    "EICHERMOT":  ["Eicher Motors", "Royal Enfield"],
    "GRASIM":     ["Grasim Industries", "Grasim"],
    "DRREDDY":    ["Dr Reddy", "Dr. Reddy's Laboratories", "Dr Reddys"],
    "CIPLA":      ["Cipla"],
    "APOLLOHOSP": ["Apollo Hospitals"],
    "DIVISLAB":   ["Divi's Laboratories", "Divis Labs", "Divi's Labs"],
    "BPCL":       ["BPCL", "Bharat Petroleum"],
    "BRITANNIA":  ["Britannia Industries", "Britannia"],
    "TATACONSUM": ["Tata Consumer", "Tata Consumer Products"],
    "HDFCLIFE":   ["HDFC Life"],
    "SBILIFE":    ["SBI Life"],
    "BAJAJFINSV": ["Bajaj Finserv"],
    "SHRIRAMFIN": ["Shriram Finance"],
    "TRENT":      ["Trent", "Westside"],
    "JIOFIN":     ["Jio Financial", "Jio Financial Services"],
    "ETERNAL":    ["Eternal", "Zomato"],
    "HINDALCO":   ["Hindalco"],
    "IOC":        ["IOC", "Indian Oil", "Indian Oil Corporation"],

    # ── Popular non-NIFTY-50 retail favourites ───────────────────────────
    "IRCTC":       ["IRCTC", "Indian Railway Catering and Tourism Corporation"],
    "SUZLON":      ["Suzlon", "Suzlon Energy"],
    "IRFC":        ["IRFC", "Indian Railway Finance"],
    "RVNL":        ["RVNL", "Rail Vikas Nigam"],
    "IRCON":       ["IRCON", "IRCON International"],
    "HAL":         ["HAL", "Hindustan Aeronautics"],
    "BEL":         ["BEL", "Bharat Electronics"],
    "BHEL":        ["BHEL", "Bharat Heavy Electricals"],
    "MAZDOCK":     ["Mazagon Dock", "Mazagon Dock Shipbuilders"],
    "COCHINSHIP":  ["Cochin Shipyard"],
    "GAIL":        ["GAIL", "GAIL India"],
    "VEDL":        ["Vedanta"],
    "TATAPOWER":   ["Tata Power"],
    "ADANIPOWER":  ["Adani Power"],
    "ADANIGREEN":  ["Adani Green", "Adani Green Energy"],
    "JINDALSTEL":  ["Jindal Steel", "Jindal Steel and Power"],
    "SAIL":        ["SAIL", "Steel Authority of India"],
    "NMDC":        ["NMDC"],
    "NATIONALUM":  ["NALCO", "National Aluminium"],
    "JSWENERGY":   ["JSW Energy"],
    "YESBANK":     ["Yes Bank"],
    "IDFCFIRSTB":  ["IDFC First Bank", "IDFC First"],
    "PNB":         ["PNB", "Punjab National Bank"],
    "BANKBARODA":  ["Bank of Baroda", "BOB"],
    "CANBK":       ["Canara Bank"],
    "UNIONBANK":   ["Union Bank", "Union Bank of India"],
    "BANDHANBNK":  ["Bandhan Bank"],
    "AUBANK":      ["AU Small Finance Bank", "AU Bank"],
    "RBLBANK":     ["RBL Bank"],
    "FEDERALBNK":  ["Federal Bank"],
    "IDEA":        ["Vodafone Idea", "Vi", "Idea"],
    "INDUSTOWER":  ["Indus Towers"],
    "LTIM":        ["LTIMindtree", "LTI Mindtree"],
    "MPHASIS":     ["Mphasis"],
    "COFORGE":     ["Coforge"],
    "PERSISTENT":  ["Persistent Systems"],
    "OFSS":        ["Oracle Financial Services", "OFSS"],
    "TATAELXSI":   ["Tata Elxsi"],
    "POLICYBZR":   ["Policybazaar", "PB Fintech"],
    "PAYTM":       ["Paytm", "One 97 Communications"],
    "NYKAA":       ["Nykaa", "FSN E-Commerce"],
    "DELHIVERY":   ["Delhivery"],
    "NAUKRI":      ["Info Edge", "Naukri"],
    "INDIAMART":   ["IndiaMART"],
    "JUSTDIAL":    ["Just Dial", "Justdial"],
    "MUTHOOTFIN":  ["Muthoot Finance"],
    "CHOLAFIN":    ["Cholamandalam"],
    "MANAPPURAM":  ["Manappuram Finance"],
    "SBICARD":     ["SBI Card", "SBI Cards"],
    "LUPIN":       ["Lupin"],
    "AUROPHARMA":  ["Aurobindo Pharma"],
    "BIOCON":      ["Biocon"],
    "TORNTPHARM":  ["Torrent Pharma", "Torrent Pharmaceuticals"],
    "ZYDUSLIFE":   ["Zydus Lifesciences", "Zydus"],
    "MANKIND":     ["Mankind Pharma"],
    "ITC":         ["ITC"],
    "DABUR":       ["Dabur", "Dabur India"],
    "MARICO":      ["Marico"],
    "GODREJCP":    ["Godrej Consumer", "Godrej Consumer Products"],
    "COLPAL":      ["Colgate", "Colgate Palmolive"],
    "VBL":         ["Varun Beverages"],
    "VOLTAS":      ["Voltas"],
    "HAVELLS":     ["Havells"],
    "SIEMENS":     ["Siemens"],
    "ABB":         ["ABB", "ABB India"],
    "CUMMINSIND":  ["Cummins"],
    "BHARATFORG":  ["Bharat Forge"],
    "BOSCHLTD":    ["Bosch"],
    "MOTHERSON":   ["Samvardhana Motherson", "Motherson"],
    "TVSMOTOR":    ["TVS Motor"],
    "ASHOKLEY":    ["Ashok Leyland"],
    "MRF":         ["MRF"],
    "BALKRISIND":  ["Balkrishna Industries", "BKT"],
    "DLF":         ["DLF"],
    "GODREJPROP":  ["Godrej Properties"],
    "OBEROIRLTY":  ["Oberoi Realty"],
    "PRESTIGE":    ["Prestige Estates", "Prestige Group"],
    "PHOENIXLTD":  ["Phoenix Mills"],
    "INDIGO":      ["IndiGo", "InterGlobe Aviation"],
    "SPICEJET":    ["SpiceJet"],
    "CONCOR":      ["CONCOR", "Container Corporation"],
    "BSE":         ["BSE", "Bombay Stock Exchange"],
    "CDSL":        ["CDSL", "Central Depository Services"],
    "MCX":         ["MCX", "Multi Commodity Exchange"],
    "ANGELONE":    ["Angel One"],
    "POLYCAB":     ["Polycab"],
    "DIXON":       ["Dixon Technologies", "Dixon"],
    "KAYNES":      ["Kaynes Technology"],
    "ZOMATO":      ["Zomato"],
    "PVRINOX":     ["PVR INOX"],
    "TATACOMM":    ["Tata Communications"],
    "TTML":        ["Tata Teleservices Maharashtra", "Tata Teleservices (Maharashtra)", "TTML"],
    "TATAGOLD":    ["Tata Gold ETF", "Tata Gold"],
    "TATSILV":     ["Tata Silver ETF", "Tata Silver"],
}
